version: 2
updates:
  # Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  labels:
    - "dependencies"
    - "github_actions"
    - "automerge"
  schedule:
    interval: "daily"

- package-ecosystem: uv
  directory: "/"
  labels:
    - "dependencies"
    - "python"
    - "automerge"
  schedule:
    interval: daily
    time: "04:00"
